### ISSUE TITLE
How to install the updated model and overcome this issues? 

### ISSUE THREAD

**Issue by XTRMsavage** [Hangover3832/ComfyUI-Hangover-Moondream#10]
![image](https://github.com/Hangover3832/ComfyUI-Hangover-Moondream/assets/90519573/4d872c2e-f032-46ba-9e3e-83adda8f7b77)
![image](https://github.com/Hangover3832/ComfyUI-Hangover-Moondream/assets/90519573/525285b7-faae-46bb-a1dc-d48e1ed6becb)

can you please provide the path where to place the model? 

Thanks

**Comment by Hangover3832** [comment]
Just toggle this switch and you should be fine:
![Unbenannt](https://github.com/Hangover3832/ComfyUI-Hangover-Moondream/assets/116489681/52190bac-2c4b-4a4b-859c-691a201b0e82)

**Comment by XTRMsavage** [comment]
Thanks, can you please tell me the path for the model? I would like to install the latest one.

**Comment by Hangover3832** [comment]
@XTRMsavage, moondream currently does not support custom model path, this is managed by the huggingface hub. It should basically update to the latest version automatic (I just tested and it does). If you think you do not have the latest, you can delete the local model in your home folder:
`C:\Users\<username>\.cache\huggingface\hub\models--vikhyatk--moondream2`
and also:
`C:\Users\<username>\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream2`
and start over.

**Comment by XTRMsavage** [comment]
Thanks. Appreciate your support. Do you have discord?

**Comment by Hangover3832** [comment]
> Thanks. Appreciate your support. 

You're welcome.

> Do you have discord?

No I'm not on discord.
