### ISSUE TITLE
Where to place model?

### ISSUE THREAD

**Issue by niko2020** [Hangover3832/ComfyUI-Hangover-Moondream#17]
moondream2 model file seems to be stored in folder:
huggingface/hub/models--vikhyatk--moondream2

can we move it somewhere like:
ComfyUI/models

?

Cheers

**Comment by niko2020** [comment]
it looks like the model files are downloaded every time I restart the comfyui server.

**Comment by Hangover3832** [comment]
See #15. Please note that automatic update and model switching feature does not work anymore this way.

**Comment by niko2020** [comment]
thank you. Is there any way to combine automatic update and not redownloading the models each time?
cheers

**Comment by Hangover3832** [comment]
Unfortunately I cannot reproduce the behavior you mentioned, this should not happen and I don't know why this happens for you. For now, best is you update the model manually if a new revision is available.

BTW, I just updated the node, it now supports custom model folder location natively, no more need to change the code, see readme. Perhaps you find time to test it?

**Comment by niko2020** [comment]
thank you for your update! I will test it.
