### ISSUE TITLE
what's the model path?

### ISSUE THREAD

**Issue by idea10101** [Hangover3832/ComfyUI-Hangover-Moondream#6]
![Quicker_20240319_213705](https://github.com/Hangover3832/ComfyUI-Hangover-Moondream/assets/161134037/0bcb39f7-5aac-4fe1-9694-6cb78c50b15b)

**Comment by Hangover3832** [comment]
Might be related to #2. Probably transformers is outdated, must be >=4.38.2. Can you please run 
`python.exe -m pip freeze | findstr "timm einops transformers"`
within the ComfyUI python_embedded folder and post the output.
